In [2]:
import tensorflow as tf
import numpy as np

In [5]:
tensor_0d = tf.constant(1)
tensor_0d

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
tensor_1d = tf.constant([1, 2, 3])
tensor_1d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [7]:
tensor_2d = tf.constant([[1, 2], [3, 4]])
tensor_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [8]:
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor_3d

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

In [9]:
tensor_4d = tf.constant([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
tensor_4d

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])>

In [12]:
tensor_5d = tf.constant([
    [[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]], 
    [[[[17, 18], [19, 20]], [[21, 22], [23, 24]]], [[[25, 26], [27, 28]], [[29, 30], [31, 32]]]]])
tensor_5d

<tf.Tensor: shape=(2, 2, 2, 2, 2), dtype=int32, numpy=
array([[[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]],



       [[[[17, 18],
          [19, 20]],

         [[21, 22],
          [23, 24]]],


        [[[25, 26],
          [27, 28]],

         [[29, 30],
          [31, 32]]]]])>

In [8]:
# casting tensor
tensor_float = tf.constant([1.2, -2.23, 0, 4], dtype=tf.float32)
tensor_int = tf.cast(tensor_float, tf.int32)
tendor_bool = tf.cast(tensor_int, tf.bool)
print(tensor_float)
print(tensor_int)
print(tendor_bool)

tf.Tensor([ 1.2  -2.23  0.    4.  ], shape=(4,), dtype=float32)
tf.Tensor([ 1 -2  0  4], shape=(4,), dtype=int32)
tf.Tensor([ True  True False  True], shape=(4,), dtype=bool)


In [9]:
# numpy array to tensor
np_array = np.array([1, 2, 3])
tensor = tf.constant(np_array)
print(np_array)
print(tensor)


[1 2 3]
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [10]:
# (batch x row x column) identity matrix
tensor_eye = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2],
    dtype=tf.int16,
    name=None); 
print(tensor_eye)

tf.Tensor(
[[[1 0 0]
  [0 1 0]
  [0 0 1]]

 [[1 0 0]
  [0 1 0]
  [0 0 1]]], shape=(2, 3, 3), dtype=int16)


In [11]:
# create tensor of shape dim with all value
tensor_fill = tf.fill(
    dims=[2, 3],
    value=8,
    name=None
)
print(tensor_fill)

tf.Tensor(
[[8 8 8]
 [8 8 8]], shape=(2, 3), dtype=int32)


In [12]:
# create a tensor of 1s
tensor_ones = tf.ones(
    shape=[3, 2],
    dtype=tf.int32,
    name=None
)

# create a tensor of 1s with shape of input tensor
tensor_ones_like = tf.ones_like(
    input=tensor_fill, # tensor_fill is 2x3 matrix
    dtype=None,
    name=None
)

print(tensor_ones) # 3x2 matrix of 1s
print(tensor_ones_like) # 2x3 matrix of 1s

tf.Tensor(
[[1 1]
 [1 1]
 [1 1]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [13]:
# exploiting tensor attributes
print(tf.shape(input=tensor_3d, out_type=tf.int32, name=None)) # a tensor containing shape of tensor_3d
print(tf.size(input=tensor_3d, out_type=tf.int32, name=None)) # number of elements in tensor_3d
print(tf.rank(input=tensor_3d, name=None)) # rank of tensor_3d

tf.Tensor([2 2 2], shape=(3,), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [14]:
# the random function depends on a seed value
# if seed value is not set, the random values will be different each time
# 2 times the same seed value will produce the same random values
tf.random.set_seed(1)

# output random values from a distribution
tensor_random_normal = tf.random.normal(
    shape=[5, 6, 4],
    mean=0.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None
)
tensor_random_uniform = tf.random.uniform(
    shape=[2, 3],
    minval=-1,
    maxval=1,
    dtype=tf.float32,
    seed=None,
    name=None
)
print(tensor_random_normal)
print(tensor_random_uniform)

tf.Tensor(
[[[-1.1012203   1.5457517   0.383644   -0.87965786]
  [-1.2246722  -0.9811211   0.08780783 -0.20326038]
  [-0.5581562  -0.72054404 -0.6259924  -0.71502596]
  [-0.34835446 -0.33646983  0.18257578  1.1085953 ]
  [ 1.2796587  -0.02147584 -0.31968883  0.37332553]
  [ 0.25279108  0.6437664   2.146308   -0.82514983]]

 [[-0.9041368   1.3948786   1.2248751   0.0586496 ]
  [-0.49213138 -0.81997806 -0.18526012 -0.39277685]
  [-0.6585226  -0.9833388   0.38883775 -1.0372448 ]
  [-1.5600569  -0.15791255 -0.3566943  -0.20044029]
  [ 1.613107    0.6796728   0.08133233  1.3380764 ]
  [ 1.1848053  -0.35381562 -0.10400175 -0.75114644]]

 [[-0.37274626 -0.87327313  0.16906022  1.0454443 ]
  [ 0.92061925 -0.36889288  0.10171467 -1.1921712 ]
  [-1.4274356   1.9076501  -0.7215866   1.2887349 ]
  [-0.4003417   0.83785444  0.5840126   1.177344  ]
  [-0.09392343 -0.72662795  1.8566561  -0.44455123]
  [ 0.87348217 -0.05244347  0.583878   -2.0958302 ]]

 [[-0.6064927  -0.25165784 -0.8024012  -0.16745

In [19]:
# tensor slicing
print(tensor_random_normal[1:4,3:,:2]) # slicing tensor_random_normal from 1 to 4 in the first dimension, 3 to end in the second dimension, and 0 to 2 in the third dimension

tf.Tensor(
[[[-1.5600569  -0.15791255]
  [ 1.613107    0.6796728 ]
  [ 1.1848053  -0.35381562]]

 [[-0.4003417   0.83785444]
  [-0.09392343 -0.72662795]
  [ 0.87348217 -0.05244347]]

 [[ 0.73638487  0.21161108]
  [-1.6936147  -0.414517  ]
  [ 1.6981432   1.0888578 ]]], shape=(3, 3, 2), dtype=float32)


### Arithmetic operation

In [22]:
# absolute value
print(tf.abs(tensor_random_uniform)) # = max(value, -value) for real number
print(tf.abs(tf.constant([5+6j, 7+8j]))) # = sqrt(real^2 + imag^2) for complex number


tf.Tensor(
[[0.02021408 0.1129365  0.1829338 ]
 [0.98498464 0.37732792 0.30830073]], shape=(2, 3), dtype=float32)
tf.Tensor([ 7.81024968 10.63014581], shape=(2,), dtype=float64)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [30]:
x1 = tf.constant([[1, 2, 3], [4, 5, 6]])
x2 = tf.constant([[4, 5, 6], [9, 0, 15]])
print(x1 + x2)
print(tf.add(x1, x2))
print(x1 - x2)
print(tf.subtract(x1, x2))

# this is not the same as matrix multiplication
print(x1 * x2)
print(tf.multiply(x1, x2))
# this is element-wise division 
print(x1 / x2)
print(tf.divide(x1, x2))
# returns 0 when  denominator is 0, instead of NaN / Inf
# does not work with all data types 
print(tf.math.divide_no_nan(x1, x2))

tf.Tensor(
[[ 5  7  9]
 [13  5 21]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 5  7  9]
 [13  5 21]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-3 -3 -3]
 [-5  5 -9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-3 -3 -3]
 [-5  5 -9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 4 10 18]
 [36  0 90]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 4 10 18]
 [36  0 90]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0.25       0.4        0.5       ]
 [0.44444444        inf 0.4       ]], shape=(2, 3), dtype=float64)
tf.Tensor(
[[0.25       0.4        0.5       ]
 [0.44444444        inf 0.4       ]], shape=(2, 3), dtype=float64)
tf.Tensor(
[[0.25       0.4        0.5       ]
 [0.44444444 0.         0.4       ]], shape=(2, 3), dtype=float64)


In [44]:
x3 = tf.constant([1, 2, 3])
# Since x1 is a 2x3 matrix and x3 is a 1x3 matrix
# x3 will be broadcasted to [[1, 2, 3], [1, 2, 3]]
print(x1 + x3)

x4 = tf.constant([[1, 2, 3], [1, 2, 3]])
print(x1 + x4)  

# The x1 + x3 is implicitly converted as x1 + x4
print((x1 + x3) == (x1 + x4))

# x1 is a 2x3 matrix 
# x5 is a 1x2 matrix
x5 = tf.constant([1, 2])
# This will raise an error because the shapes are not convertible
###### print(x1 + x5) ######

tf.Tensor(
[[2 4 6]
 [5 7 9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[2 4 6]
 [5 7 9]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ True  True  True]
 [ True  True  True]], shape=(2, 3), dtype=bool)


In [40]:
operand1 = tf.constant([5, 2, 3, 6, 4, 6])
operand2 = tf.constant([[7], [5], [3]])
print(tf.shape(operand1))
print(tf.shape(operand2))
print(operand1 + operand2)

# operand1 (1x6) will be broadcasted to [[5, 2, 3, 6, 4, 6], [5, 2, 3, 6, 4, 6], [5, 2, 3, 6, 4, 6]]
# operand2 (3x1) will be broadcasted to [[7, 7, 7], [5, 5, 5], [3, 3, 3]]
# both then become 3x6 matrix

tf.Tensor([6], shape=(1,), dtype=int32)
tf.Tensor([3 1], shape=(2,), dtype=int32)
tf.Tensor(
[[12  9 10 13 11 13]
 [10  7  8 11  9 11]
 [ 8  5  6  9  7  9]], shape=(3, 6), dtype=int32)


In [46]:
print(tf.maximum(operand1, operand2))
print(tf.minimum(operand1, operand2))

tf.Tensor(
[[7 7 7 7 7 7]
 [5 5 5 6 5 6]
 [5 3 3 6 4 6]], shape=(3, 6), dtype=int32)
tf.Tensor(
[[5 2 3 6 4 6]
 [5 2 3 5 4 5]
 [3 2 3 3 3 3]], shape=(3, 6), dtype=int32)


In [54]:
# return the index of the maximum value
print(tf.argmax(tensor_3d))
# return the index of the minimum value
print(tf.argmin(tensor_3d))

t1 = tf.constant([1,2,3,4,5,6,7])
t2 = tf.constant([0,2,3,90,5,78,7])
# return a tensor of boolean values indicating if the elements are equal
print(tf.equal(t1, t2))
# return a tensor of boolean values indicating if the elements are not equal
print(tf.not_equal(t1, t2))
# return a tensor with value[i] = t1[i] ^ t2[i]
print(tf.pow(t1, t2))


tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int64)
tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int64)
tf.Tensor([False  True  True False  True False  True], shape=(7,), dtype=bool)
tf.Tensor([ True False False  True False  True False], shape=(7,), dtype=bool)
tf.Tensor([     1      4     27      0   3125      0 823543], shape=(7,), dtype=int32)


In [61]:
# return the sum of all elements in the tensor
print(tf.reduce_sum(
    input_tensor=tensor_3d,
    # if None all elements are summed, otherwise sum is done along the axis
    axis=None,
    # if True, keep the dimensions of the reduced axes 
    keepdims=False,
    name=None))
# Similarly, there are reduce_min, reduce_max, reduce_mean, reduce_all, reduce_any, reduce_prod
# reduce_all returns True if all elements are True, False otherwise
# reduce_any returns False if all elements are False, True otherwise
# reduce_prod returns the product of all elements

# sigmoid function 
print(tf.sigmoid(tensor_random_normal))

tf.Tensor(36, shape=(), dtype=int32)
tf.Tensor(
[[[0.24951132 0.8242993  0.5947517  0.29324868]
  [0.22711527 0.27266937 0.52193785 0.44935912]
  [0.36397415 0.3272732  0.34841982 0.32848924]
  [0.4137815  0.41666725 0.5455176  0.7518671 ]
  [0.78239167 0.49463123 0.42075157 0.59226227]
  [0.56286335 0.65560436 0.8953233  0.3046716 ]]

 [[0.28820112 0.80136997 0.7729203  0.5146582 ]
  [0.3793916  0.3057683  0.45381698 0.403049  ]
  [0.34107155 0.2722298  0.5960029  0.26168197]
  [0.17363848 0.46060368 0.41176003 0.45005703]
  [0.8338423  0.6636657  0.5203219  0.79217345]
  [0.7658107  0.41245747 0.47402298 0.32057154]]

 [[0.4078776  0.2945737  0.5421647  0.7398991 ]
  [0.71516824 0.40880856 0.5254067  0.23287085]
  [0.19349857 0.8707549  0.3270437  0.7839329 ]
  [0.40123025 0.6980131  0.6419902  0.7644699 ]
  [0.4765364  0.32593516 0.8649067  0.39065704]
  [0.7054697  0.48689213 0.64195925 0.10950277]]

 [[0.35285965 0.4374155  0.3095121  0.4582337 ]
  [0.1652398  0.304631   0.6362632