In [2]:
import tensorflow as tf

operand1 = tf.constant([[1.0, 2.0, 3.0, 4.0], [5.2, 4.1, 8.5, 10]])
operand2 = tf.constant([[7.0, 8.0, 9.0, 10.0], [1.2, 3.1, 5.5, 7]])

In [11]:
print(tf.linalg.matmul(operand1, operand2, transpose_a=False, transpose_b=True, a_is_sparse=False, b_is_sparse=False, adjoint_a=False, adjoint_b=False, name=None))
print(operand1 @ tf.transpose(operand2, perm=[1, 0])) 
print(tf.linalg.matmul(operand1, operand2, transpose_a=True, transpose_b=False, a_is_sparse=False, b_is_sparse=False, adjoint_a=False, adjoint_b=False, name=None))


tf.Tensor(
[[ 90.   51.9]
 [245.7 135.7]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 90.   51.9]
 [245.7 135.7]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 13.24      24.119999  37.6       46.399998]
 [ 18.92      28.71      40.55      48.699997]
 [ 31.2       50.35      73.75      89.5     ]
 [ 40.        63.        91.       110.      ]], shape=(4, 4), dtype=float32)


In [7]:
var1 = tf.Variable([[1.0, 2.0, 3.0, 4.0], [5.2, 4.1, 8.5, 10]])
print(var1)
var1.assign_sub([[7.0, 8.0, 9.0, 10.0], [1.2, 3.1, 5.5, 7]])
print(var1)
var1.assign_add([[7.0, 8.0, 9.0, 10.0], [1.2, 3.1, 5.5, 7]])
print(var1)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5.2,  4.1,  8.5, 10. ]], dtype=float32)>